<?php
    require('connect_mysql.php');
    $sql_query="UPDATE score_1_1 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_2 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_3 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_4 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_5 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_6 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_7 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_8 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_9 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_10 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_11 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_12 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_13 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_14 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_15 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_16 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_17 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_18 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_19 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_20 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_21 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_22 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_23 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_24 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_25 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_26 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_27 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_28 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_29 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_1_30 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");

    $sql_query="UPDATE score_2_1 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_2 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_3 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_4 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_5 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_6 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_7 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_8 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_9 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_10 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_11 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_12 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_13 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_14 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_15 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_16 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_17 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_18 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_19 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_20 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_21 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_22 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_23 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_24 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_25 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_26 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_27 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_28 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_29 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_2_30 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");

    $sql_query="UPDATE score_3_1 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_2 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_3 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_4 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_5 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_6 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_7 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_8 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_9 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_10 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_11 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_12 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_13 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_14 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_15 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_16 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_17 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_18 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_19 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_20 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_21 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_22 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_23 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_24 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_25 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_26 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_27 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_28 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_29 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    $sql_query="UPDATE score_3_30 SET 1am=NULL,2am=NULL,3am=NULL,4am=NULL,5am=NULL,1amo=NULL,2amo=NULL,3amo=NULL,4amo=NULL,5amo=NULL,1pm=NULL,2pm=NULL,3pm=NULL,4pm=NULL,5pm=NULL,1pmo=NULL,2pmo=NULL,3pmo=NULL,4pmo=NULL,5pmo=NULL";
    $result=mysqli_query($db_link,$sql_query) or die("刪除失敗，請洽詢相關人員");
    header('Location:admin_other.php');
?>